# Generated by Django 2.2.4 on 2021-06-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='easy_apply_app.User'),
        ),
    ]
