# Generated by Django 2.2.4 on 2021-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_app', '0002_auto_20210603_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='easy_apply_app.User'),
        ),
    ]
