# Generated by Django 3.2.4 on 2021-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_app', '0004_auto_20210603_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paswsword',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
