# Generated by Django 2.2.4 on 2021-06-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_app', '0005_auto_20210603_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='married',
        ),
    ]
