# Generated by Django 2.2.4 on 2021-06-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_apply_app', '0006_auto_20210603_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='specialist',
            field=models.CharField(choices=[('', ''), ('Engineering', 'Engineering'), ('Doctor', 'Doctor'), ('Pharmacy', 'Pharmacy'), ('IT', 'IT'), ('Science', 'Science'), ('Math', 'Math'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Phisycs', 'Phisycs'), ('Sport', 'Sport'), ('Finance', 'Finance'), ('Managment', 'Managment')], default='', max_length=255),
        ),
    ]
