# Generated by Django 2.2.4 on 2021-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_app', '0005_auto_20210604_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
